
name: image-search-engine-app
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - pip==19.3.1
  - numpy==1.17.3
  - pandas==0.25.3
  - scikit-learn==0.21.3
  - scipy==1.3.2
  - flask==1.1.1
  - matplotlib==3.1.1
  - seaborn==0.9.0
  - tensorflow-gpu==2.1.0
  - jupyter==1.0.0
  - certifi
  - waitress==1.3.1
  - pyyaml==5.1.2
  - pip:
 #   - faiss==1.5.3
    - opencv-python==4.2.0.34
    - tqdm==4.45.0
    - hnswlib==0.3.2.0